### ISSUE TITLE
Saw duplicate message at subscriber app

### ISSUE THREAD

**Issue by vksingh70** [real-logic/Aeron#71] opened 2015-03-16 21:43 UTC
I was testing a streaming app (https://github.com/strangelydim/Aeron.git)  with smaller term size and observed a duplicate message at subscriber.
1. Started MediaDriver at subscriber machine
2. Started subscriber app
   java -cp aeron-samples/build/libs/samples.jar -Daeron.dir.data=/tmp/aeron/data -Daeron.dir.conductor=/tmp/aeron/conductor -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true uk.co.real_logic.aeron.samples.BasicSubscriberWithFragDefragAdaptor

3. Started MediaDriver a producer machine
java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true -Daeron.term.buffer.length=131072 -Daeron.term.buffer.max.length=65536 uk.co.real_logic.aeron.driver.MediaDriver

4. Started producer app 
java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true uk.co.real_logic.aeron.samples.BasicPublisherWithFragmentation

===>>> message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 48 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 8328 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 16608 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 24888 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 33168 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 41448 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 49728 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 58008 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 66288 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 74568 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 82848 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 91128 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 99408 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 107688 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 115968 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 48 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 8328 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 16608 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 24888 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 33168 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 41448 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 49728 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 58008 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 66288 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 74568 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 82848 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 91128 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 99408 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 107688 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba8 term offset 115968 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 48 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 8328 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 16608 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 24888 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 33168 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 41448 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 49728 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 58008 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 66288 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 74568 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 82848 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 91128 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 99408 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 107688 (8204@0)
message to stream 10 from session 2a84b003 term id 8e320ba9 term offset 115968 (8204@0)
====>>>> message to stream 10 from session 2a84b003 term id 8e320ba7 term offset 48 (8204@0)
java.lang.Exception: Verifiable message per-message checksum invalid; received -2131986731 but calculated -1317191303
	at uk.co.real_logic.aeron.tools.MessageStream.putNext(MessageStream.java:162)
	at uk.co.real_logic.aeron.samples.BasicSubscriberWithFragDefragAdaptor.lambda$reassembledStringMessage$7(BasicSubscriberWithFragDefragAdaptor.java:175)
	at uk.co.real_logic.aeron.samples.BasicSubscriberWithFragDefragAdaptor$$Lambda$3/5300014.onData(Unknown Source)
	at uk.co.real_logic.aeron.FragmentAssemblyAdapter.onData(FragmentAssemblyAdapter.java:94)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogReader.read(LogReader.java:101)
	at uk.co.real_logic.aeron.Connection.poll(Connection.java:92)
	at uk.co.real_logic.aeron.Subscription$$Lambda$13/32856234.apply(Unknown Source)
	at uk.co.real_logic.agrona.concurrent.AtomicArray.doLimitedAction(AtomicArray.java:185)
	at uk.co.real_logic.aeron.Subscription.poll(Subscription.java:89)
	at uk.co.real_logic.aeron.samples.BasicSubscriberWithFragDefragAdaptor.main(BasicSubscriberWithFragDefragAdaptor.java:92)

See the ===>>> mark in the output for duplicate message.

**Comment by tmontgomery** [comment] 2015-03-19 20:45
I suspect this is due to the term length max being too small. This controls the template file size. Which is used to zero out. In that case, the end of a "cleaned" term could contain junk and something like this could be seen.

I'll look into this and see if I can reproduce and then put a check in place to prevent.

**Comment by tmontgomery** [comment] 2015-03-19 22:23
What arguments are used to start the subscriber media driver?

**Comment by vksingh70** [comment] 2015-03-20 19:12
Not 100% sure, but I think it was the following:
java -cp aeron-samples/build/libs/samples.jar -Daeron.dir.data=/tmp/aeron/data -Daeron.dir.conductor=/tmp/aeron/conductor -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true uk.co.real_logic.aeron.driver.MediaDriver

After one instance, I have never been able to reproduce it.

**Comment by tmontgomery** [comment] 2015-03-31 17:48
I think I know what this could possibly be. And will be trying to reproduce.

The max being too small for the size on the publisher AND the subscriber being on a separate driver without such a restriction.

**Comment by tmontgomery** [comment] 2015-04-20 16:24
I think with the latest change to #87, this could be gone. So, closing this for now. Please re-open if seen again.

**Closed by tmontgomery** 2015-04-20 16:24 UTC
Labels: bug, enhancement
