### ISSUE TITLE
Re-creation Aeron instance and publications on error

### ISSUE THREAD

**Issue by SemenChernyy** [real-logic/aeron#492] opened 2018-03-19 18:04 UTC
Hi,

Can you say what should be the strategy of handling Aeron errors (e.g. Timeout in ClientConductor)?
Will it be correct to re-create Aeron and the publishers (say, application is only publishing)?

Basically, I am interested if the following strategy is viable and goes alogn with Aeron design and implementation point of view:
offer a new message to Aeron publisher (instance of io.aeron.Publication).
If publication fails after N attempts, try to re-create Aeron publisher (call Aeron.addPublication()).
If this fails (e.g. ClientConductor is closed) then close current Aeron instance and re-create it (call Aeron.connect()), then re-create publishers again.

The reason of implementing this strategy is to mitigate any hiccups in Aeron caused by Aeron/application/hardware. 

I was running test-application with this strategy implemented on Win. Application periodically calls FullGC in order to cause timeout in ClientConductor. 
The strategy works but once I got VM crashed with `EXCEPTION_ACCESS_VIOLATION` and stacktrace:
> Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 395  sun.misc.Unsafe.getLongVolatile(Ljava/lang/Object;J)J (0 bytes) @ 0x0000000005ec720f [0x0000000005ec71c0+0x4f]
j  io.aeron.logbuffer.TermAppender.rawTailVolatile()J+11
j  io.aeron.Publication.offer(Lorg/agrona/DirectBuffer;IILio/aeron/ReservedValueSupplier;)J+41
j  io.aeron.Publication.offer(Lorg/agrona/DirectBuffer;II)J+5

aeron version is 1.2.5
vm_info: Java HotSpot(TM) 64-Bit Server VM (25.92-b14) for windows-amd64 JRE (1.8.0_92-b14)

Thank you!

**Comment by tmontgomery** [comment] 2018-03-19 21:01
A service timeout on the Aeron client indicates the client has not been responsive for the client liveness timeout in the driver. Thus the driver, in most cases, will consider the client to be dead.

This means the client should close and recreate all publications and subscriptions.

You should not need to recreate publications on failed offers. Even after a number of attempts. Unless the return indicates CLOSED. And in that case, it is most likely that the client timed out on the driver and all publications and subscriptions should be closed and recreated.

In general, handling timeouts of the client by closing and recreating is necessary. And should probably be considered a clean restart of the application.

Timeouts like this, if you are getting them often, indicates a need to provision the application better (much less STW pauses from GCs, less resource starvation from threading, etc.). You can increase the client liveness timeout on the driver to account for some pauses, but this is not very useful unless the cause of pauses is known and accounted for.

**Comment by mjpt777** [comment] 2018-03-19 21:06
It is also a good strategy to keep your software up to date. Both your Aeron version and JDK are very out of date.

**Closed** 2018-03-29 04:17 UTC
