### ISSUE TITLE
[QUESTION] Client gets connected twice to the server.

### ISSUE THREAD

**Issue by PrabhakarTayenjam** [real-logic/aeron#1047] opened 2020-08-25 09:49 UTC
SCENARIO:
Server is written in C and using an external media driver.
Client is written in java and it is starting the media driver from inside the code.
Both the server and client are running in the same machine.

PROBLEM:
Whenever the publisher in client is connecting to the subscriber in server, it is connecting twice. Below is the log messages that I got when I try to connect the client to the server. This log is generated whenever a client is connected.

```aeron_messaging.c|on_client_connected|59|New client connected from source: 127.0.0.1:5842```
```aeron_messaging.c|on_client_connected|59|New client connected from source: 127.0.0.1:5842```

Here the source is same.
But when I connect using a C client using the external media driver, this doesn't happen.

QUESTION:
Why is the java client connecting twice? Is this because of the java client starting its own media driver?

**Comment by mjpt777** [comment] 2020-09-07 18:51
How are you tracking the connect? Unless you post a minimal test case to reproduce this we cannot investigate.

**Comment by mjpt777** [comment] 2020-09-17 10:25
Closing due to no follow up or test case.

**Closed by mjpt777** 2020-09-17 10:25 UTC
