### ISSUE TITLE
Questions about disconnection/reconnection and IPC

### ISSUE THREAD

**Issue by aslondon** [real-logic/Aeron#327] opened 2017-03-19 11:55 UTC
I'm beginning to migrate our existing trading application from a proprietary system to Aeron/SBE (in Java). For now I'm building a throw-away spike to familiarise myself with these technologies, which I'm new to. So I have a trading app that accepts SBE-encoded FIX messages (NewOrderSingle etc.), executes a (placeholder for now) business logic and outputs SBE-encoded FIX messages like execution report, cancel reject, etc. Hence the app has both a subscriber and a publisher. Everything happens on the Aeron thread, as per my understanding of the best practices.

On the other side I have a (spike of a) end-to-end testing framework that sends the messages, listens to the execution reports and does the assertions. As a first example, it sends 1000 NewOrderSingle messages in quick sequence (no sleeps) and makes sure that all the execution reports are received. The client is implemented as one (for now) Junit test, with an `@BeforeClass` that creates context, subscriber and publisher, and an `@AfterClass` that closes everything.

**Problem 1** On UDP unicast, everything runs perfectly the first time. The problems begin if I re-run the tests a second time (i.e. after the test has been executed and the process has died). In this case the client either doesn't receive anything back or stops receiving after a certain timeout (that seems to be always more or less the same). At some point I see an Unavailable image and the client stops receiving execution reports. At this point everything is corrupt and I have to bounce the server! I understand that it takes time to detect a disconnection but I would have thought that disconnecting one subscriber and connecting a new one (it's a completely new process) even in quick sequence shouldn't be a problem: the old one will simply be timed out, whereas my impression is that the same connection is reused, so when it times out the whole thing stops working. This happens even if from the application I re-create a brand new publisher and publication after disconnection.

**Problem 2** If I move from UDP to IPC everything breaks as in the messages arrive to the subscriber corrupted. When I pick up the `templateId` to dispatch to the appropriate decoder, this is always 0. This never happens other than in IPC, never seen it before in UDP or in unit tests, so I think the problem is in the Aeron bit (i.e. something's wrong in my Aeron code, rather than in my SBE code). Is switching to IPC simply a matter of changing the channel to `CommonContext.IPC_CHANNEL` or is there anything else to change?

I'm using a BusySpinIdleStrategy, external MediaDriver, FragmentAssembler. I do check every time whether the publication is connected or not and I do capture all the return values from `offer()` and they're all good.

Any ideas what I'm doing wrong? I can try and post the code but I would have to sanitise it with extreme care. If needed I'll try and extract a minimal example.

Many thanks

**Comment by tmontgomery** [comment] 2017-03-19 17:54
For UDP unicast, a new subscription will pick up on an existing publication. By closing a subscription, you are not closing the connection, actually. At least initially. If you rapidly create a new subscription while a publication is active, you will see that publication be picked back up by the new subscription. If you create multiple publications, then each will be seen by the same subscription individually. Even unicast, it acts more like pub/sub than a single connection.

For IPC, it is pretty much the same.

For the corruption, are you rewrapping the SBE codecs on the encoder and decoder sides correctly each time? And also, when you send are you sending the correct length? SBE is very sensitive to correct usage. Incorrect usage can result in message corruption.

**Comment by aslondon** [comment] 2017-03-20 14:58
Hi Todd, thanks for your Sunday reply.

What you're saying confirms my suspicion i.e. the publication is not closed and gets reused the next time. So what is the best practice to defend oneself against a situation like this? This is an issue for me as I would like to be able to play around with my tests, start and stop them, without having to bounce the application every time. Is an application-level heartbeat the way forward? So that when the test side disconnects I can close the publication on the application side and open a new one the next time?

For the corruption, I believe I'm using SBE correctly as everything's fine both with UDP and in unit tests every single time, so this is really weird. I'll investigate more.

Many thanks again

**Comment by tmontgomery** [comment] 2017-03-20 16:25
If you are closing the Publication, then it should not be reused.... unless you create a new Publication before closing the previous one. What you mentioned, I thought, was closing the Subscription.

Once unreferenced, Publications linger for a bit. But new Publications should not use it. They will create a new one. However, since Publications lingers, they may send any pending data that was not sent out.

If you want to handle a situation where a controlled Subscription and Publication need to coordinate without shutting down the driver, you can do it a couple ways. 

One is to let the Subscription linger in the app a little while after the Publication has been closed until the Image has gone unavailable (meaning the Publication has lingered and then timed out from the Subscriptions perspective). This takes about 10 seconds (assuming all data has been flushed).

Another option is to make sure the Publication has sent all data and been received. Put a formatted message in the stream to indicate the end. Close, the Publication. Wait for the Subscription to see the end message. Then create a new Publication. Keep the Subscription around. You should see new messages just fine. And as the application has waited for the end of one stream before starting the next, it should be fairly simple.

And another option is to use the Header sessionId on the Subscription side to manage interleaved messages coming from multiple Publications.

**Comment by mjpt777** [comment] 2017-03-31 09:14
I'm going to close this so that a more specific issue can be raised if reproducible test case can be created. This seems like a bug in the application code.

**Closed by mjpt777** 2017-03-31 09:14 UTC
