### ISSUE TITLE
Add protection for multiple drivers on same machine

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#14] opened 2014-11-05 16:27 UTC
Need to protect the shared directories.

**Comment by tmontgomery** [comment] 2015-04-17 16:04
Bumping this for need.

One option is possibly to use the driver KA value in the cnc file as an indication of driver existence. This is already updated by the driver.

If I new driver starts and there is an existing cnc file, it checks the `nanoTime` in it. If too old, then it cleans out everything (warning as it does so). But if not, then it exits and won't launch indicating an existing driver is already using the directory.

Thoughts?

**Comment by tmontgomery** [comment] 2015-04-30 18:12
Proposal for directory management:

* The default namespace for the Aeron directory based on Java system property `user.name`. Thus looking like: `system-TMP-or-/dev/shm/aeron-user.name`. For example, if on Linux and /dev/shm is accessible and username is "tmont", then location would be `/dev/shm/aeron-tmont/`.

* Liveness of a driver using a given directory is indicated by the CnC file `ManyToOneRingBuffer` used for commands to the driver. This liveness is already used by the clients. Checking this liveness will be packaged into `CnCFileDescriptor` as a method for ease of use externally.

* Removal of `aeron.dir.delete.on.exit`. The default will be __NOT__ to delete on exit as Java is incredibly bad at this when shutdown in an abnormal way.

* Addition of `aeron.dir.delete.on.start`. The default will be false. This indicates whether the directory should be deleted on startup or not irregardless of the existence of a CnC file and driver liveness.

* When a driver starts up, the following would be done:
    * If no directory, then create and start
    * If directory and `aeron.dir.delete.on.start` set to __true__, then delete directory contents and start, __WARN__ of directory existence
    * If directory, but no CnC file in directory, delete directory contents and start, __WARN__ of directory existence
    * If directory, CnC file exists, but liveness is too old, then delete directory contents and start, __WARN__ of directory existence
    * If directory, CnC file exists, liveness is young, and `aeron.dir.delete.on.start` set to __false__ then __DO NOT START__, log error and exit.

**Comment by jessefugitt** [comment] 2015-04-30 18:54
Defaulting to a value with the user.name makes sense to me as well as removing the auto-delete on exit feature if it doesn't work in all cases.  However, I would suggest adding a API to do a manual directory cleanup  (mostly for the embedded media driver use case) that would at give the user an optional way of deleting the directory on a clean shutdown if they wanted that.

For a case with multiple processes on a machine with each running an embedded media driver, it would be ideal if the associated aeron dir would be auto-deleted when the process that is running that embedded media driver stops, but this is probably not possible.  However, you also don't want to end up with a bunch of directories in the temp space scattered about (one for each run of an embedded media driver).  Along with the suggestion of having a manual API to do cleanup, it might also be nice if the embedded media drivers defaulted to a location inside the new user specific aeron dir as a convenient place to clean up crashed processes (assuming the unlikely event that anyone running Aeron ever hits a bug or closes uncleanly).  
Something like:
/dev/shm/aeron-tmont/default - as described above
/dev/shm/aeron-tmont/embedded/{uuid} - these get generated by embedded media drivers and can be cleaned up manually via an API at shutdown or manually via the command line later for no longer running processes
/dev/shm/aeron-tmont/{somename} - this is the recommended directory layout if you wanted to create a shared media driver that is used with more than one process and you don't want to collide with the default

To clarify, my suggestion is more around default directory layout and I'm not suggesting any changes to the startup and shutdown behavior being proposed above (no special case behavior based on different directories).

**Comment by brianhorst** [comment] 2015-04-30 21:33
Is there going to be an effort to be able to start a media driver and have it resume where a previous one left? Right now, if a media driver goes down, all clients need to close and re-create publications and subscriptions (which kind of sucks). The proposed file management doesn't seem to take into account this possible feature. In this case, a separate lock file may be needed.

I also like the ability to have the driver delete the files it created without starting a new one. An API call on the MediaDriver would be sufficient if we plan on removing the delete on close feature. I think it's OK to leave files if the driver terminates abnormally.

**Comment by tmontgomery** [comment] 2015-05-01 17:02
@brianhorst One of the points of cleaning up at the start is to have the media driver always start with a clean slate. Hopefully a media driver failing will be less and less likely. But if it does, the app should consider that to be a pretty big failure and should restart everything anyway. In the future, we could look at doing that and making it easier, though.

@jessefugitt I like the idea of an API to do cleanup. That is a very good suggestion and will incorporate it.

For an embedded driver, I'm not sold on it automatically generating a random dir name. Would like to hear @mjpt777 , @lbradstreet , and @MichaelDrogalis weigh in on. For an embedded driver, I think it is more important to control the location directly and think it would be good to force that, really.

**Comment by MichaelDrogalis** [comment] 2015-05-01 17:15
I'm used to frequently using UUIDs as directory names when I'm the one who has to name something that I consider ephemeral to my application. If that's what Aeron offered, I'd be totally okay with it.

**Comment by rlankenau** [comment] 2015-05-01 17:20
@MichaelDrogalis That's what I was thinking.  For an embedded driver, you're dealing with ephemeral state, and it should be created and deleted along with the application.  In that case, it doesn't really matter what the directory is called as long as it doesn't collide with others.  The case where the directory is left after a crash isn't optimal, but it does mean that you have the data for crash analysis...

A standalone driver is much more of a managed resource, and should have a well-known name/location, and can have its data lifecycle managed independently of the process accessing the data.

**Comment by mjpt777** [comment] 2015-05-01 17:21
I like the data being left after a crash so it can help diagnose.

**Comment by mjpt777** [comment] 2015-05-01 17:23
It would be possible to design the media driver to support restart but that would be a fair bit of work. For now best to assume it would not restart and pick up residual data. We should work out how to make the driver very solid. Does not matter so much if clients die.

**Comment by mjpt777** [comment] 2015-05-01 17:24
If the driver is embedded would it not makes sense to name the file after the PID?

**Comment by tmontgomery** [comment] 2015-05-01 17:26
naming after the PID would also help with identifying the driver...

**Comment by rlankenau** [comment] 2015-05-01 17:27
My thought was that a PID was less portable than simply using a UUID, and didn't really provide a great deal of identifying information, especially if you're debugging a crash.

**Comment by mjpt777** [comment] 2015-05-01 17:31
The PID approach is much easier for debugging a running system.

**Comment by rlankenau** [comment] 2015-05-01 17:34
I agree that having the PID makes it easier to identify the directory of a running driver.

If that's the long-term solution, we should probably put some code into Agrona to fetch the PID in a portable manner.

**Comment by MichaelDrogalis** [comment] 2015-05-01 17:35
Does that assume you can recover the process ID of the driver before it crashes? What about the case where the driver cashes very quickly?

**Comment by mjpt777** [comment] 2015-05-01 17:35
@rlankenau http://stackoverflow.com/questions/35842/how-can-a-java-program-get-its-own-process-id

**Comment by rlankenau** [comment] 2015-05-01 17:42
I'm fine with using ManagementFactory.getRuntimeMXBean().getName() as the unique part, and I think @jessefugitt suggested a good directory layout to avoid the multi-user issues the commit I put in was intended to fix.

**Comment by tmontgomery** [comment] 2015-05-01 19:18
@rlankenau can you explain the multi-user issue? Doesn't just using `user.name` address a multi-user collision?

**Comment by tmontgomery** [comment] 2015-05-01 19:21
@MichaelDrogalis the driver could crash on startup before it could create the directory. But not sure we can fix that. There could be a crash in a static that happens before `main`. Or the parent directory could not be writable by the user, etc.

**Comment by tmontgomery** [comment] 2015-05-01 19:24
BTW, IIRC Windows "re-uses" PIDs pretty aggressively. Also, PIDs roll pretty quick in a busy system.... or one that has extended uptime.

**Comment by rlankenau** [comment] 2015-05-01 19:31
@tmontgomery 
Right, your original layout using `user.name` works to address the collision, but I think using `/dev/shm/user.name/default`, `/dev/shm/user.name/embedded`, etc. results in a much cleaner layout.  If you use the top-level directory (i.e. `/dev/shm/user.name/`) It gets a bit ugly when you want to run an embedded driver and a standalone driver on the same box as the same user.

Both you and Jesse had good suggestions, I think Jesse's is a bit cleaner.

So if we put all of this together, we have:

Default
- `/dev/shm/user.name/default`

Embedded
- `/dev/shm/user.name/pid@hostname`

Explicitly Named
- `/dev/shm/user.name/default`

If there's quite a bit of work to be done to allow driver restart on an existing directory, maybe we should just default to clearing the selected directory on both startup and shutdown to allow both a clean start and a clean stop.  We can change the default when we revisit the driver restart idea.

An abnormal stop will leave the directory for analysis.

**Comment by tmontgomery** [comment] 2015-05-01 19:44
@rlankenau good point about the same user doing an embedded and standalone driver at the same time.

**Comment by mjpt777** [comment] 2015-05-02 13:12
As  general principle we should rank usability higher than outright flexibility. Engineers often don't consider the needs of the many users to their detriment.

**Comment by tmontgomery** [comment] 2015-06-30 16:32
Going to bite this off myself soon.

**Comment by tmontgomery** [comment] 2015-06-30 18:12
Proposal for directory management:

* The default namespace for the Aeron directory based on Java system property `user.name`. Thus looking like: `system-TMP-or-/dev/shm/aeron-user.name`. For example, if on Linux and /dev/shm is accessible and username is "tmont", then location would be `/dev/shm/aeron-tmont/`.

* `launchEmbedded` will generate a UUID-based directory under the `user.name`. Removal of launchEmbedded from EmbeddedThroughput and EmbeddedPingPong as this is hampering tuning and monitoring with AeronStat.

* Liveness of a driver using a given directory is indicated by the CnC file `ManyToOneRingBuffer` used for commands to the driver. This liveness is already used by the clients. Checking this liveness will be packaged into `CnCFileDescriptor` as a method for ease of use externally. The timeout value for the driver would be based on the client liveness. This is currently, `Aeron.DEFAULT_MEDIA_DRIVER_TIMEOUT_MS`. This would be moved to `CommonContext` so it can be accessed by the driver and client.

* Removal of `aeron.dir.delete.on.exit`. The default will be __NOT__ to delete on exit as Java is incredibly bad at this when shutdown in an abnormal way.

* Addition of `aeron.dir.delete.on.start`. The default will be false. This indicates whether the directory should be deleted on startup or not irregardless of the existence of a CnC file and driver liveness.

* CommonContext API for manual cleanup of driver directory. Suggested by @jessefugitt 

* When a driver starts up, the following would be done:
    * If no directory, then create and start
    * If directory and `aeron.dir.delete.on.start` set to __true__, then delete directory contents and start, __WARN__ of directory existence
    * If directory, but no CnC file in directory, delete directory contents and start, __WARN__ of directory existence
    * If directory, CnC file exists, but liveness is too old, then delete directory contents and start, __WARN__ of directory existence
    * If directory, CnC file exists, liveness is young, and `aeron.dir.delete.on.start` set to __false__ then __DO NOT START__, log error and exit.

* I would like to add a means for the MediaDriver to see a property file in its directory and read values in from it.

**Comment by mjpt777** [comment] 2015-06-30 21:58
+1

**Comment by tmontgomery** [comment] 2015-07-01 20:34
Changes (aside from property file) are in.

**Comment by tmontgomery** [comment] 2015-07-01 20:34
Going to move property file request to its own issue and close this.

**Closed by tmontgomery** 2015-07-01 20:34 UTC
Labels: enhancement
