### ISSUE TITLE
[Bug] Spy connector doesn't work with endpoint port chosen by OS

### ISSUE THREAD

**Issue by InversionSpaces** [real-logic/aeron#1445] opened 2023-04-04 12:07 UTC
### Description

Spy subscription doesn't connect when MDC publication with dynamic control mode was created with control endpoint port set to `0` in order for OS to choose the port.

### Steps to reproduce

* Create publication `aeron:udp?control=localhost:0|control-mode=dynamic|ssc=true` with `streamId=0`.
* Retrieve publication `localAddr` via `localSocketAddresses`
* Create subscription `aeron-spy:aeron:udp?control=<localAddr>|control-mode=dynamic` with `streamId=0`
* Try to publish and receive some messages

### Expected result

Messages are transmitted successfully.

### Result

No image becomes available for subscription. 

### Code snippet

https://gist.github.com/InversionSpaces/e0b8cbd3c3fcb5fb905c4b6985aac14d

### Note

The exact same code works if either:
* Static port is set instead of `0`
* Prefix `aeron-spy:` is removed from subscription

**Comment by mikeb01** [comment] 2023-04-05 21:07
I can confirm that this doesn't work at present.  I will look into this in more detail, but I think there is a simpler approach to get the desired behaviour.

Create the publication with a tag:
```
final long pubTag = aeron.nextCorrelationId();

final String pubUri = new ChannelUriStringBuilder("aeron:udp?control=localhost:0|control-mode=dynamic|ssc=true")
    .tags(pubTag, null)
    .build();
```
Then create the spy subscription with the tag
```
final String spyUri = new ChannelUriStringBuilder()
    .prefix(ChannelUri.SPY_QUALIFIER)
    .media("udp")
    .tags(pubTag, null)
    .build();
```
This works and it also means that the code doesn't need to wait until the port is bound to set up the spy.

--
One question, when using a system assigned port for the control address, how are your remote subscriptions going to determine which port to use?

**Comment by mikeb01** [comment] 2023-04-06 04:37
I've done a deeper dive in the code and I'm going to close this issue.  It is effectively working as it should.  Trying to make this scenario work in the fashion would be flaky at best.  It illustrate why it won't work lets look at the resolved URIs for the publication and the spy:
```
publication: aeron:udp?control=localhost:0|control-mode=dynamic|ssc=true
spy: aeron:udp?control=localhost:32456|control-mode=dynamic|ssc=true  // assuming the bound port is 32456
```
They don't actually match.  They happen to correlate to the same port, but this association is easily broken if the publication is closed and opened again as the port will be different.  Wildcard ports do create some tricky issues around matching.  Therefore in the [documentation](https://github.com/real-logic/aeron/wiki/Channel-Configuration#wildcard-ports) we recommend using tags.  Admittedly the documentation refers to using subscriptions, the concept holds for control addresses with publications and spies.

**Closed by mikeb01** 2023-04-06 04:37 UTC

**Comment by InversionSpaces** [comment] 2023-04-06 09:47
@mikeb01 

I don't get your point about "They don't actually match" at all. If they don't match in this scenario, then the same applies to all URIs in documentation section you mentioned, but to my mind such workflow is clearly stated as possible. Also, if they do not match, then why the same approach works if subscription is not a spy?

About "this association is easily broken if the publication is closed and opened again as the port will be different" - it is understandable and even desirable behavior. To not lose this publication tags could be used. And in my workflow it is actually the case, but I omitted it here.

You suggest to use tags to resolve the issue. I couldn't find if tags work across different machines, but I guess they don't, do they?

---

Here is my use case in brief. I have some discovery and coordination service that helps my components to exchange all information they need for establishing connections. One component creates publication with wildcard port and publish assigned port so others could fetch it. Components do not know in advance if they are on the same machine, but if it is the case, creating spy subscription would be great optimization. 

Now I see that my problem could be resolved by using non spy subscriptions if a component is on separate machine and tag is it is on the same machine.

**Comment by mikeb01** [comment] 2023-04-06 21:51
We have concept of matching which applies to the correlation of resources that are created within the same driver.  The best way to explain this is from the perspective of a subscription, but it applies to publishers & spies as well.  If we create two subscriptions:

```
Subscription subA = aeron.addSubscription("aeron:udp?endpoint=localhost:9090", 1001);
Subscription subB = aeron.addSubscription("aeron:udp?endpoint=localhost:9090", 1002);
```

The first subscription will create a receiver bound to port 9090, but when we create `subB` we can't create a receiver on the same port as we can't bind to the same port twice.  Therefore the driver will match `subB` with `subA` because they share the same endpoint. Then `subB` will use the same receiver and Aeron will multiplex the two streams (`1001` and `1002`) over the same port.  If the two subscriptions have the same stream id, then they will also share the image buffer memory and just retain separate position values.  The concept of matching on endpoint** has be an important internal feature since the inception of Aeron.

** It is actually more detailed than that, but the simplification suits for now

Later on we needed to add support for wildcard ports, but unfortunately the use of wildcards breaks matching somewhat.  Lets consider creating two subscriptions with wildcard ports:

```
Subscription subA = aeron.addSubscription("aeron:udp?endpoint=localhost:0", 1001);
Subscription subB = aeron.addSubscription("aeron:udp?endpoint=localhost:0", 1002);
```
If we considered these two endpoint a match then we would only ever be able to bind to a single OS assigned port at one time.  Therefore we have set it up so that you can't match endpoints that use wildcards.  In the scenario above these will create subscriptions on two different OS assigned ports.  However, there may be occasions where we want to have the two subscriptions share the same OS assigned port, therefore we reused our tags feature to allow users to reference a subscription or publication that is created earlier.

I had considered making matching work based on the resolved OS assigned port, but that creates other complications, e.g. the port used can change over time and you could end up with transient matches that you don't expect if the ports happened to match.  Using tags creates a stronger logical association.

So to the MDC publication/spy case that you are looking at.  The reason it works for a normal subscription is that a normal subscription listens on a port.  There is no actual matching in this case.  A spy subscription does not listen on a port, instead it is using the ability to match a publication and then attach itself to the term buffers used by the publication and read those directly (this is the optimisation).  Because a wildcard port is used in the control address of the publication it is not possible to construct a spy URI that will match with that publication.  Therefore again we recommend the use of tags is it creates a strong logical link between the publication and the spy.  There is potentially an argument that spies should always use tags, but we added tags after we added spies.

> You suggest to use tags to resolve the issue. I couldn't find if tags work across different machines, but I guess they don't, do they?

They don't.  Tags (as well as spies) only work for resources on the same driver.
